// Encrypts the hidden story (arg/story.mjs, private) into public/js/arg-data.js.
// Fragment n: its clue and hook are encrypted with the key of fragment n-1, its log with its own key, and its
// own key is wrapped once per accepted answer (PBKDF2). Without the answers, the published file reveals nothing
// beyond the first clue. Run after editing the story: node scripts/arg-build.mjs
import fs from 'node:fs';
import path from 'node:path';
import { webcrypto as crypto } from 'node:crypto';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '..');
const enc = new TextEncoder();
const b64 = (buf) => Buffer.from(buf).toString('base64');
export const ITERATIONS = 150000;
/** Same normalisation as public/js/arg.js. */
export const norm = (s) => String(s).normalize('NFD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9]/g, '');

async function passKey(answer, salt) {
  const base = await crypto.subtle.importKey('raw', enc.encode(norm(answer)), 'PBKDF2', false, ['deriveKey']);
  return crypto.subtle.deriveKey({ name: 'PBKDF2', hash: 'SHA-256', salt, iterations: ITERATIONS }, base, { name: 'AES-GCM', length: 256 }, false, ['encrypt']);
}
async function seal(key, value, aad) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv, additionalData: enc.encode(aad) }, key, enc.encode(JSON.stringify(value)));
  return { iv: b64(iv), ct: b64(ct) };
}

export async function build(chapters) {
  let prevKey = null;
  const out = [];
  for (const [i, c] of chapters.entries()) {
    const n = i + 1;
    const raw = crypto.getRandomValues(new Uint8Array(32));
    const key = await crypto.subtle.importKey('raw', raw, 'AES-GCM', false, ['encrypt']);
    const wraps = [];
    for (const a of c.answers) {
      const salt = crypto.getRandomValues(new Uint8Array(16));
      const w = await seal(await passKey(a, salt), b64(raw), `wrap|${n}`);
      wraps.push({ salt: b64(salt), ...w });
    }
    wraps.sort(() => Math.random() - 0.5);   // the order says nothing about the answers
    out.push({
      n, month: c.month, title: n === 1 ? c.title : null,
      // Fragment 1 is readable by anyone who finds the terminal; the rest needs the previous key.
      clue: prevKey ? await seal(prevKey, { title: c.title, clue: c.clue }, `clue|${n}`) : { title: c.title, clue: c.clue },
      hook: c.hook == null ? null : prevKey ? await seal(prevKey, c.hook, `hook|${n}`) : c.hook,
      wraps,
      log: await seal(key, c.log, `log|${n}`),
    });
    prevKey = key;
  }
  return { v: 1, iterations: ITERATIONS, chapters: out };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { CHAPTERS } = await import(pathToFileURL(path.join(root, 'arg', 'story.mjs')).href);
  const data = await build(CHAPTERS);
  const file = path.join(root, 'public', 'js', 'arg-data.js');
  fs.writeFileSync(file, `// Generated by scripts/arg-build.mjs — do not edit.\nexport default ${JSON.stringify(data)};\n`);
  console.log(`✔ ${data.chapters.length} fragments chiffrés → public/js/arg-data.js`);
}
